services:
  app:
    build: .
    image: ghcr.io/vatax3/giftmanager:latest
    environment:
      - SQLITE_PATH=/app/data/giftmanager.db
    volumes:
      - app_data:/app/data
    ports:
      - "80:8000"
    restart: unless-stopped

volumes:
  app_data:
